### ISSUE TITLE
Examples should not be released

### ISSUE THREAD

**Issue by zambrovski** [toolisticon/camel-spring-boot-testutils#1]
Only the library should be released into Maven central.

**Comment by jangalinski** [comment]
I did this by only including the module "examples" in a profile that is deactivated by default. in local builds, I activate it, for the maven release its inactive and thus the examples are not deployed.
Annoying manual step: since examples are invisible during deployment, you have to set the next snapshot version manually. Or integrate that step in the pipeline.

**Comment by zambrovski** [comment]
Have you seen, how it is implemented? I assume `activeByDefault` is wrong?

**Comment by tobiasstamann** [comment]
I would recommend not to disable modules in build by profile.

You can use the following to just skip the deployment in the examples pom:

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

Doing that you won't have any problems with the release plugin and version numbers and you have excluded the artifacts from deployment to the repository.
This affects only the deploy goal - install to the local repository is not affected and still working.
